/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.Frm_facturap;
import static Vistas.enviar_cliente.recibe;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hugo
 */
public class agregarcliente extends javax.swing.JFrame {
    
    String codigo,referencia,cantidad,marca,valor;
    String bd ="ventas";
             String NOMBRE;
             String login = "root";
             String password = "";
             String url = "jdbc:mysql://localhost/"+bd; // esta es la conexion

    /**
     * Creates new form agregarcliente
     */
             
    
    public agregarcliente() {
        initComponents();
        setLocationRelativeTo(null);
        recibeCliente.setVisible(false);
    }
    public void deshabilitara(){
       txtnombre.setText("");
       txtapellido.setText("");
       txtcodigo.setText("");
       txtcodigo.requestFocus();
       txttelefono.setText("");
       txtdireccion.setText("");
     
       txtnombre.setEditable(false);
       txtapellido.setEditable(false);
       txtcodigo.setEditable(false);
       txttelefono.setEditable(false);
       txtdireccion.setEditable(false);
     
     
       botonNuevo.setVisible(true);
       btn_cancelara.setVisible(false);
 
    }
    public void habilitara(){
       txtnombre.setText("");    
       txtapellido.setText("");
       txtcodigo.setText("");
       txtcodigo.requestFocus();
       txttelefono.setText("");
       txtdireccion.setText("");
     
       txtnombre.setEditable(true);
       txtapellido.setEditable(true);
       txtcodigo.setEditable(true);
       txttelefono.setEditable(true);
       txtdireccion.setEditable(true);
     
     
       botonNuevo.setVisible(false);
       btn_cancelara.setVisible(true);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        btn_guardara = new org.edisoncor.gui.button.ButtonSeven();
        btn_cancelara = new org.edisoncor.gui.button.ButtonSeven();
        jLabel1 = new javax.swing.JLabel();
        recibeCliente = new javax.swing.JTextField();
        botonNuevo = new org.edisoncor.gui.button.ButtonSeven();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText(" NIT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 70, -1));

        txtcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 220, 40));

        jLabel5.setBackground(new java.awt.Color(239, 255, 239));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText(" Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, -1));

        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 220, 40));

        jLabel8.setBackground(new java.awt.Color(239, 255, 239));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Apellido");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, -1));

        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        txtapellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtapellidoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 220, 40));

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 220, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText(" Teléfono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText(" Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, -1));

        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
        });
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 220, 40));

        btn_guardara.setBackground(new java.awt.Color(204, 204, 204));
        btn_guardara.setText("Agregar");
        btn_guardara.setColorBrillo(new java.awt.Color(255, 255, 255));
        btn_guardara.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_guardara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardaraActionPerformed(evt);
            }
        });
        jPanel1.add(btn_guardara, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 107, 51));

        btn_cancelara.setBackground(new java.awt.Color(204, 204, 204));
        btn_cancelara.setText("Cancelar");
        btn_cancelara.setColorBrillo(new java.awt.Color(255, 255, 255));
        btn_cancelara.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_cancelara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelaraActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cancelara, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, 49));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Cliente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));
        jPanel1.add(recibeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 40, 40));

        botonNuevo.setBackground(new java.awt.Color(204, 204, 204));
        botonNuevo.setText("Nuevo");
        botonNuevo.setColorBrillo(new java.awt.Color(255, 255, 255));
        botonNuevo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(botonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, -1, 49));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')
        evt.consume();// TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoKeyTyped

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        txtnombre.setText (txtnombre.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        Character c;
        c = evt.getKeyChar();
        if(!Character.isLetter(c) && c != com.sun.glass.events.KeyEvent.VK_SPACE){
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyReleased
        txtapellido.setText (txtapellido.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoKeyReleased

    private void txtapellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidoKeyTyped
        Character c;
        c = evt.getKeyChar();
        if(!Character.isLetter(c) && c != com.sun.glass.events.KeyEvent.VK_SPACE){
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0'|| c>'9')
        evt.consume();
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        txtdireccion.setText (txtdireccion.getText().toUpperCase());        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void btn_guardaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardaraActionPerformed
        // CODIGO GUARDAR
        if (txtnombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Falta el Nombre del Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
            txtnombre.requestFocus();
        }else {
            if (txtapellido.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Faltan los Apellidos del Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
                txtapellido.requestFocus();
            }else {
                if (txtcodigo.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Falta la Cedula o Nit del Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
                }else
                if (txttelefono.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Falta el Telefono del Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
                }else
                if (txtdireccion.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Falta la Direccion del Cliente","Advertencia",JOptionPane.WARNING_MESSAGE);
                }else
                try {
                    String bd = "ventas";
                    String login = "root";
                    String password = "";
                    String url = "jdbc:mysql://localhost/" + bd;
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(Frm_Articulo.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    Connection conn = (Connection) DriverManager.getConnection(url,login,password);
                    Statement consulta = conn.createStatement();

                    Statement consulta1=conn.createStatement(); // crea una variable que se encargue del código de sql
                    ResultSet r= consulta1.executeQuery("select cod_cliente from cliente");
                    int bandera=0;//para saber si el codigo esta o no en la base de datos (si sale con cero no esta)
                    while(r.next()){
                        //JOptionPane.showMessageDialog(null,"entro a la consulta1");
                        if(txtcodigo.getText().equals(r.getString(1))){//si el codigo de la tabla es igual a algun codigo de la base de datos
                            bandera=1;
                            //JOptionPane.showMessageDialog(null,"BANDERA= "+bandera);

                        }
                    }
                    //JOptionPane.showMessageDialog(null,"salio de la consulta1");

                    if(bandera==0){//Si el codigo no esta inserto una nuevo registro a la base de datos
                        //JOptionPane.showMessageDialog(null,"esta por hacer un insert");
                        consulta.executeUpdate("insert into cliente (cod_cliente,nombres,apellidos,dirrecion,telefono)  values('"+txtcodigo.getText()+"','"+txtnombre.getText()+"','"+txtapellido.getText()+"','"+txtdireccion.getText()+"','"+txttelefono.getText()+"')");

                    }else{//si el codigo esta,actualizo la informacion del producto
                        //JOptionPane.showMessageDialog(null,"esta por hacerun update");
                        consulta.executeUpdate("UPDATE cliente SET nombres='"+txtnombre.getText()+"',apellidos='"+txtapellido.getText()+"',dirrecion='"+txtdireccion.getText()+"',telefono='"+txttelefono.getText()+"'WHERE cod_cliente='"+txtcodigo.getText()+"'");
                    }
                    
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"El CLIENTE"+" "+ txtcodigo.getText()+" "+"DE NOMBRE"+" "+txtnombre.getText()+" "+"YA EXISTE");

                }
            }
        } 
        
        if(recibeCliente.getText().equals("3")){
            Frm_facturap.cb2.addItem(txtnombre.getText()+" "+txtapellido.getText());
            Frm_facturap.cb2.setSelectedItem(txtnombre.getText()+" "+txtapellido.getText());
            this.setVisible(false);
        }else{
           if(recibeCliente.getText().equals("4")){
                frm_remito.cbCliente.addItem(txtnombre.getText()+" "+txtapellido.getText());
                frm_remito.cbCliente.setSelectedItem(txtnombre.getText()+" "+txtapellido.getText());
                this.setVisible(false);
            }else{
                if(recibeCliente.getText().equals("5")){
                    Frm_presupuesto.cb2.addItem(txtnombre.getText()+" "+txtapellido.getText());
                    Frm_presupuesto.cb2.setSelectedItem(txtnombre.getText()+" "+txtapellido.getText());
                    this.setVisible(false);
                }  
            }
        }
    }//GEN-LAST:event_btn_guardaraActionPerformed

    private void btn_cancelaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelaraActionPerformed
        deshabilitara();
    }//GEN-LAST:event_btn_cancelaraActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        habilitara();
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregarcliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new agregarcliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static org.edisoncor.gui.button.ButtonSeven botonNuevo;
    public static org.edisoncor.gui.button.ButtonSeven btn_cancelara;
    private org.edisoncor.gui.button.ButtonSeven btn_guardara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField recibeCliente;
    public static javax.swing.JTextField txtapellido;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables

    private void deshabilitar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
