/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Hugo
 */
public class frm_posicionIVA extends javax.swing.JFrame {

    /**
     * Creates new form frm_facturasPorFecha
     */
    public frm_posicionIVA() {
        initComponents();
        
        //icono del sistema
        try{
            setIconImage(new ImageIcon(getClass().getResource("/img/iconoSistema64.png")).getImage());
        }catch(Exception e){
            
        }
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setearFecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMonthChooser1 = new com.toedter.calendar.JMonthChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnMostrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        fechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        fechaHasta = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Reporte final de facturación");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 530, 50));

        btnMostrar.setBackground(new java.awt.Color(5, 52, 99));
        btnMostrar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("MOSTRAR");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 190, 40));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel9.setText("Desde:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 120, 50));

        fechaDesde.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel1.add(fechaDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 190, 50));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel7.setText("Hasta:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 120, 50));

        fechaHasta.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jPanel1.add(fechaHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setearFecha() {      
        Calendar c2 = new GregorianCalendar();
        fechaDesde.setCalendar(c2); 
        fechaHasta.setCalendar(c2); 
    }
    public void obtenerFecha(){
        String fecha="", totalIvaCompra="0.00",totalFacturasCompras="0.00",totalFacturasVentas="0.00", totalIvaVenta="0.00",totalIvaCreditoCompra="0.00",totalIvaCreditoVenta="0.00",totalNotaCreditoVenta="0.00",totalNotaCreditoCompra="0.00";
        /*
        int año = JAño.getYear();
        int mes = JMes.getMonth();
        
        if((mes+1)<10 ){
            fecha = (año+"-0"+(mes+1)+'%');
        }else{
            fecha = (año+"-"+(mes+1)+'%');      
        }
        
        switch (mes+1) {
            case 1:
                nombreMes="ENERO "+año;
            break;
            case 2:
                nombreMes="FEBRERO "+año;
            break;
            case 3:
                nombreMes="MARZO "+año;
            break;
            case 4:
                nombreMes="ABRIL "+año;
            break;
            case 5:
                nombreMes="MAYO "+año;
            break;
            case 6:
                nombreMes="JUNIO "+año;
            break;
            case 7:
                nombreMes="JULIO "+año;
            break;
            case 8:
                nombreMes="AGOSTO "+año;
            break;
            case 9:
                nombreMes="SEPTIEMBRE "+año;
            break;
            case 10:
                nombreMes="OCTUBRE "+año;
            break;
            case 11:
                nombreMes="NOVIEMBRE "+año;
            break;
            case 12:
                nombreMes="DICIEMBRE "+año;
            break;

     }*/
        
        
        
        String fechaDesde1="", fechaDesde2="";
        int añoDesde = fechaDesde.getCalendar().get(Calendar.YEAR);
        int mesDesde = fechaDesde.getCalendar().get(Calendar.MONTH);
        int diaDesde = fechaDesde.getCalendar().get(Calendar.DAY_OF_MONTH);

        if((mesDesde+1)<10 && (diaDesde>=10)){
            fechaDesde1 = (añoDesde+"-0"+(mesDesde+1)+"-"+diaDesde);
            fechaDesde2 = (diaDesde+"/0"+(mesDesde+1)+"/"+añoDesde);
        }else{
            if(((mesDesde+1)<10 && (diaDesde<10))){
                fechaDesde1 = (añoDesde+"-0"+(mesDesde+1)+"-0"+diaDesde);
                fechaDesde2 = ("0"+diaDesde+"/0"+(mesDesde+1)+"/"+añoDesde);
            }else{
                fechaDesde1 = (añoDesde+"-"+(mesDesde+1)+"-"+diaDesde);
                fechaDesde2 = (diaDesde+"/"+(mesDesde+1)+"/"+añoDesde);
            }
        }
        
        String fechaHasta1="",fechaHasta2="";
        int añoHasta = fechaHasta.getCalendar().get(Calendar.YEAR);
        int mesHasta = fechaHasta.getCalendar().get(Calendar.MONTH);
        int diaHasta = fechaHasta.getCalendar().get(Calendar.DAY_OF_MONTH);

        if((mesHasta+1)<10 && (diaHasta>=10)){
            fechaHasta1 = (añoHasta+"-0"+(mesHasta+1)+"-"+diaHasta);
            fechaHasta2 = (diaHasta+"/0"+(mesHasta+1)+"/"+añoHasta);
        }else{
            if(((mesHasta+1)<10 && (diaHasta<10))){
                fechaHasta1 = (añoHasta+"-0"+(mesHasta+1)+"-0"+diaHasta);
                fechaHasta2 = ("0"+diaHasta+"/0"+(mesHasta+1)+"/"+añoHasta);
            }else{
                fechaHasta1 = (añoHasta+"-"+(mesHasta+1)+"-"+diaHasta);
                fechaHasta2 = (diaHasta+"/"+(mesHasta+1)+"/"+añoHasta);
            }
        }
            //JOptionPane.showMessageDialog(this, fechaDesde1);
            //JOptionPane.showMessageDialog(this, fechaHasta1);
        //JOptionPane.showMessageDialog(this,totalConIva+" "+totalSinIva);
        
        Connection miconexion = conexion.ObtenerConexion();
        
        int bandera=0;
        try{
            Statement consulta1=miconexion.createStatement(); // crea una variable que se encargue del código de sql
            ResultSet r= consulta1.executeQuery("select SUM(total_con_iva - total_sin_iva) from compra where fecha BETWEEN '"+fechaDesde1+"' AND '"+fechaHasta1+"'");
            while(r.next()){
               totalIvaCompra=r.getString(1);
               bandera=1;
            }
            ResultSet r2= consulta1.executeQuery("select SUM(total_con_iva - total_sin_iva) from factura where fecha BETWEEN '"+fechaDesde1+"' AND '"+fechaHasta1+"'");
            while(r2.next()){
               totalIvaVenta=r2.getString(1);

               bandera=1;
            }
            
            ResultSet r3= consulta1.executeQuery("select SUM(total_con_iva - total_sin_iva), SUM(total_con_iva) from nota_credito_compra where fecha BETWEEN '"+fechaDesde1+"' AND '"+fechaHasta1+"'");
            while(r3.next()){
               totalIvaCreditoCompra=r3.getString(1);
               totalNotaCreditoCompra=r3.getString(2);
               bandera=1;
            }
            
            ResultSet r4= consulta1.executeQuery("select SUM(total_con_iva - total_sin_iva), SUM(total_con_iva) from nota_credito where fecha BETWEEN '"+fechaDesde1+"' AND '"+fechaHasta1+"'");
            while(r4.next()){
               totalIvaCreditoVenta=r4.getString(1);
               totalNotaCreditoVenta=r4.getString(2);
               bandera=1;
            }
            ResultSet r5= consulta1.executeQuery("select SUM(total_con_iva) from factura where fecha BETWEEN '"+fechaDesde1+"' AND '"+fechaHasta1+"'");
            while(r5.next()){
               totalFacturasVentas=r5.getString(1);
            }
            ResultSet r6= consulta1.executeQuery("select SUM(total_con_iva) from compra where fecha BETWEEN '"+fechaDesde1+"' AND '"+fechaHasta1+"'");

            while(r6.next()){
               totalFacturasCompras=r6.getString(1);
            }
        }catch(Exception e){
            System.out.println("1"+e);
        }
        //JOptionPane.showMessageDialog(this, totalConIva+" "+totalSinIva);
        if(totalIvaCompra==null){
           totalIvaCompra="0.00"; 
        }
        if(totalIvaVenta==null){
           totalIvaVenta="0.00"; 
        }
        if(totalIvaCreditoCompra==null){
           totalIvaCreditoCompra="0.00"; 
        }
        if(totalIvaCreditoVenta==null){
           totalIvaCreditoVenta="0.00"; 
        }
        if(totalFacturasVentas==null){
           totalFacturasVentas="0.00"; 
        }
        if(totalFacturasCompras==null){
           totalFacturasCompras="0.00"; 
        }
        if(totalNotaCreditoVenta==null){
           totalNotaCreditoVenta="0.00"; 
        }
        if(totalNotaCreditoCompra==null){
           totalNotaCreditoCompra="0.00"; 
        }

       // if (!totalIvaCompra.equals("0.00")){
            /*double conIvaCompra = Double.parseDouble(totalConIvaCompra);
            conIvaCompra=Math.round(conIvaCompra * 100.0)/ 100.0;
            TotalConIvaCompraString=(String.format("%.2f",conIvaCompra));
            double sinIvaCompra = Double.parseDouble(totalSinIvaCompra);
            sinIvaCompra=Math.round(sinIvaCompra * 100.0)/ 100.0;
            double ivaCompra= conIvaCompra-sinIvaCompra;
            valorIvaCompra=(String.format("%.2f",ivaCompra));*/
        //}
        
        
       /* if(totalConIvaVenta==null){
           totalConIvaVenta="0.000"; 
        }
        if (!totalConIvaVenta.equals("0.000")){
            double conIvaVenta = Double.parseDouble(totalConIvaVenta);
            conIvaVenta=Math.round(conIvaVenta * 100.0)/ 100.0;
            TotalConIvaVentaString=(String.format("%.2f",conIvaVenta));
            double sinIvaVenta = Double.parseDouble(totalSinIvaVenta);
            sinIvaVenta=Math.round(sinIvaVenta * 100.0)/ 100.0;
            double ivaVenta= conIvaVenta-sinIvaVenta;
            valorIvaVenta=(String.format("%.2f",ivaVenta));
        }*/
       double condicionIvaCompra=0.00, condicionIvaVenta=0.00, condicionFinal=0.00;
       condicionIvaCompra = Double.parseDouble(totalIvaCompra) - Double.parseDouble(totalIvaCreditoCompra);
       condicionIvaVenta = Double.parseDouble(totalIvaVenta) - Double.parseDouble(totalIvaCreditoVenta);
       condicionFinal=condicionIvaVenta- condicionIvaCompra;
       
       double totalVentas= Double.parseDouble(totalFacturasVentas)-Double.parseDouble(totalNotaCreditoVenta);
       double totalCompras= Double.parseDouble(totalFacturasCompras)-Double.parseDouble(totalNotaCreditoCompra);
        
        Map parametros = new HashMap();
        //parametros.put("codf",fecha);
        parametros.put("fechaDesde",fechaDesde1);
        parametros.put("fechaHasta",fechaHasta1);
        parametros.put("fechaDesde1",fechaDesde2);
        parametros.put("fechaHasta1",fechaHasta2);
        parametros.put("totalIvaCompra",totalIvaCompra);
        parametros.put("totalIvaVenta",totalIvaVenta);
        parametros.put("totalIvaCreditoCompra",totalIvaCreditoCompra);
        parametros.put("totalIvaCreditoVenta",totalIvaCreditoVenta);
        parametros.put("condicionIvaCompra",String.format("%.2f",condicionIvaCompra).replace(",","."));
        parametros.put("condicionIvaVenta",String.format("%.2f",condicionIvaVenta).replace(",","."));
        parametros.put("condicionFinal",String.format("%.2f",condicionFinal).replace(",","."));
        parametros.put("totalFacturasVentas",totalFacturasVentas);
        
        parametros.put("totalFacturasCompras",totalFacturasCompras);
        parametros.put("totalCreditoVentas",totalNotaCreditoVenta);
        parametros.put("totalCreditoCompras",totalNotaCreditoCompra);
        parametros.put("totalVentas",String.format("%.2f",totalVentas).replace(",","."));
        parametros.put("totalCompras",String.format("%.2f",totalCompras).replace(",","."));
        parametros.put("facturacionTotal",String.format("%.2f",totalVentas-totalCompras).replace(",","."));
        
        try{ 
            String reporte="posicionIva.jasper";
            JasperPrint informe =JasperFillManager.fillReport(reporte, parametros,miconexion);
            JasperViewer ventanavisor=new JasperViewer(informe,false);
            ventanavisor.setTitle("Reporte de facturación");
            ventanavisor.setVisible(true); 
        } catch (Exception e) {
            System.out.println("2"+e);
            JOptionPane.showMessageDialog(this, e.getMessage()+"");
        }
    }
    
    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        obtenerFecha();
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_posicionIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_posicionIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_posicionIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_posicionIVA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_posicionIVA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private com.toedter.calendar.JDateChooser fechaDesde;
    private com.toedter.calendar.JDateChooser fechaHasta;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JMonthChooser jMonthChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
