/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * menu.java
 *
 * Created on 23/04/2010, 10:34:15 AM
 */

package Vistas;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Alberto
 */
public class menu extends javax.swing.JFrame {

    /** Creates new form menu */
    public menu() {
        initComponents();
        
        setTitle("Sistema De Facturacion System Electronic");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        M_conectar.setEnabled(false);
          
    }

    public void iniciar(){
        //botonArticulos.setBackground(new java.awt.Color(0,0,0));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        conectado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_tipo = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        botonArticulos1 = new javax.swing.JButton();
        botonArticulos2 = new javax.swing.JButton();
        botonArticulos3 = new javax.swing.JButton();
        botonArticulos4 = new javax.swing.JButton();
        botonArticulos5 = new javax.swing.JButton();
        botonArticulos6 = new javax.swing.JButton();
        botonArticulos7 = new javax.swing.JButton();
        botonArticulos8 = new javax.swing.JButton();
        botonArticulos9 = new javax.swing.JButton();
        botonArticulos10 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        M_deinicio = new javax.swing.JMenu();
        M_conectar = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        M_desconectar = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem13 = new javax.swing.JMenuItem();
        M_registrar = new javax.swing.JMenu();
        javax.swing.JMenuItem Articulos = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Clientes = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menu_empleados = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        Proveedores = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Facturas = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem11 = new javax.swing.JMenuItem();
        M_consultar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        M_reportes = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem7 = new javax.swing.JMenuItem();
        mantenimiento = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        M_acerca = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem12.setText("jMenuItem12");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("RODAMIENTOS DEL CARIBE");
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelImage1.setBackground(new java.awt.Color(204, 204, 204));
        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/principalfondo.png"))); // NOI18N

        conectado.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        conectado.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel2.setText("BIENVENIDO USUARIO:");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 15)); // NOI18N
        jLabel3.setText("TIPO:");

        lb_tipo.setFont(new java.awt.Font("Cambria", 0, 17)); // NOI18N
        lb_tipo.setText("jLabel1");

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));
        panelBotones.setOpaque(false);

        botonArticulos1.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos1.setText("Articulos");
        botonArticulos1.setFocusCycleRoot(true);
        botonArticulos1.setFocusable(false);
        botonArticulos1.setRequestFocusEnabled(false);
        botonArticulos1.setRolloverEnabled(false);
        botonArticulos1.setVerifyInputWhenFocusTarget(false);
        botonArticulos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos1ActionPerformed(evt);
            }
        });

        botonArticulos2.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos2.setText("Proveedores");
        botonArticulos2.setFocusable(false);
        botonArticulos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos2ActionPerformed(evt);
            }
        });

        botonArticulos3.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos3.setText("Clientes");
        botonArticulos3.setFocusable(false);
        botonArticulos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos3ActionPerformed(evt);
            }
        });

        botonArticulos4.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos4.setText("Remitos");
        botonArticulos4.setFocusable(false);
        botonArticulos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos4ActionPerformed(evt);
            }
        });

        botonArticulos5.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos5.setText("Facturas");
        botonArticulos5.setFocusable(false);
        botonArticulos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos5ActionPerformed(evt);
            }
        });

        botonArticulos6.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos6.setText("Empleados");
        botonArticulos6.setFocusable(false);
        botonArticulos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos6ActionPerformed(evt);
            }
        });

        botonArticulos7.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        botonArticulos7.setText("Presupuestos");
        botonArticulos7.setFocusable(false);
        botonArticulos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos7ActionPerformed(evt);
            }
        });

        botonArticulos8.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos8.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botonArticulos8.setText("Reporte Facturas");
        botonArticulos8.setFocusable(false);
        botonArticulos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos8ActionPerformed(evt);
            }
        });

        botonArticulos9.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos9.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botonArticulos9.setText("Reporte Clientes");
        botonArticulos9.setFocusable(false);
        botonArticulos9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos9ActionPerformed(evt);
            }
        });

        botonArticulos10.setBackground(new java.awt.Color(51, 153, 255));
        botonArticulos10.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        botonArticulos10.setText("Reporte Articulos");
        botonArticulos10.setFocusable(false);
        botonArticulos10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArticulos10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonArticulos10)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(botonArticulos1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArticulos8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonArticulos1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonArticulos2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(botonArticulos3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(botonArticulos6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonArticulos5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonArticulos4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonArticulos7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonArticulos8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonArticulos9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonArticulos10, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_tipo))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conectado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1211, Short.MAX_VALUE))
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(conectado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lb_tipo))
                .addGap(8, 8, 8))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        M_deinicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        M_deinicio.setText("Inicio");
        M_deinicio.setToolTipText("Inicio");
        M_deinicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        M_conectar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        M_conectar.setBackground(new java.awt.Color(255, 255, 255));
        M_conectar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        M_conectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/connect.png"))); // NOI18N
        M_conectar.setText("Conectar");
        M_conectar.setToolTipText("conectar");
        M_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_conectarActionPerformed(evt);
            }
        });
        M_deinicio.add(M_conectar);
        M_deinicio.add(jSeparator13);

        M_desconectar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        M_desconectar.setBackground(new java.awt.Color(255, 255, 255));
        M_desconectar.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        M_desconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/disconnect.png"))); // NOI18N
        M_desconectar.setText("Desconectar");
        M_desconectar.setToolTipText("Desconectar");
        M_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_desconectarActionPerformed(evt);
            }
        });
        M_deinicio.add(M_desconectar);
        M_deinicio.add(jSeparator14);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem13.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar.png"))); // NOI18N
        jMenuItem13.setText("Salir");
        jMenuItem13.setToolTipText("Salir");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        M_deinicio.add(jMenuItem13);

        jMenuBar1.add(M_deinicio);

        M_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/listarn.png"))); // NOI18N
        M_registrar.setText("Registrar");
        M_registrar.setToolTipText("Registrar");
        M_registrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        Articulos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        Articulos.setBackground(new java.awt.Color(255, 255, 255));
        Articulos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Articulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/articulo.png"))); // NOI18N
        Articulos.setText("Articulos");
        Articulos.setToolTipText("Registrar Articulo");
        Articulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArticulosActionPerformed(evt);
            }
        });
        M_registrar.add(Articulos);
        M_registrar.add(jSeparator3);

        Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        Clientes.setBackground(new java.awt.Color(255, 255, 255));
        Clientes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        Clientes.setText("Clientes");
        Clientes.setToolTipText("Registrar Cliente");
        Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesActionPerformed(evt);
            }
        });
        M_registrar.add(Clientes);
        M_registrar.add(jSeparator4);

        menu_empleados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        menu_empleados.setBackground(new java.awt.Color(255, 255, 255));
        menu_empleados.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        menu_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        menu_empleados.setText("Empleados");
        menu_empleados.setToolTipText("Registrar Empleado");
        menu_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_empleadosActionPerformed(evt);
            }
        });
        M_registrar.add(menu_empleados);
        M_registrar.add(jSeparator5);

        Proveedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        Proveedores.setBackground(new java.awt.Color(255, 255, 255));
        Proveedores.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/provedor.png"))); // NOI18N
        Proveedores.setText("Proveedores");
        Proveedores.setToolTipText("Registrar Proveedor");
        Proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedoresActionPerformed(evt);
            }
        });
        M_registrar.add(Proveedores);

        jMenuBar1.add(M_registrar);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        jMenu2.setText("Facturar");
        jMenu2.setToolTipText("");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        Facturas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        Facturas.setBackground(new java.awt.Color(255, 255, 255));
        Facturas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        Facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        Facturas.setText(" Facturas");
        Facturas.setToolTipText("Registrar Factura");
        Facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturasActionPerformed(evt);
            }
        });
        jMenu2.add(Facturas);
        jMenu2.add(jSeparator15);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/factura.png"))); // NOI18N
        jMenuItem10.setText("Remitos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);
        jMenu2.add(jSeparator2);

        jMenuItem11.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem11.setText("Presupuestos");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        M_consultar.setBackground(new java.awt.Color(0, 204, 255));
        M_consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        M_consultar.setText("Consultar");
        M_consultar.setToolTipText("Consultar");
        M_consultar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem1.setText("Clientes");
        jMenuItem1.setToolTipText("Consultar Clientes");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        M_consultar.add(jMenuItem1);
        M_consultar.add(jSeparator7);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        jMenuItem2.setText("Empleados");
        jMenuItem2.setToolTipText("Consultar Empleados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        M_consultar.add(jMenuItem2);
        M_consultar.add(jSeparator8);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/provedor.png"))); // NOI18N
        jMenuItem3.setText("Provedores");
        jMenuItem3.setToolTipText("Consultar Proveedores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        M_consultar.add(jMenuItem3);
        M_consultar.add(jSeparator9);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/articulo.png"))); // NOI18N
        jMenuItem4.setText("Articulos");
        jMenuItem4.setToolTipText("Consultar Articulos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        M_consultar.add(jMenuItem4);

        jMenuBar1.add(M_consultar);

        M_reportes.setBackground(new java.awt.Color(0, 204, 255));
        M_reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/repor.png"))); // NOI18N
        M_reportes.setText("Reportes");
        M_reportes.setToolTipText("Reportes");
        M_reportes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pagos.png"))); // NOI18N
        jMenuItem5.setText("Factura");
        jMenuItem5.setToolTipText("Reportes De Facturas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        M_reportes.add(jMenuItem5);
        M_reportes.add(jSeparator10);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/articulo.png"))); // NOI18N
        jMenuItem6.setText("Articulos");
        jMenuItem6.setToolTipText("Reportes De Articulos");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        M_reportes.add(jMenuItem6);
        M_reportes.add(jSeparator11);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenuItem7.setText("Clientes");
        jMenuItem7.setToolTipText("Reportes De Clientes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        M_reportes.add(jMenuItem7);

        jMenuBar1.add(M_reportes);

        mantenimiento.setText("Mantenimiento");
        mantenimiento.setToolTipText("Mantenimiento");
        mantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mantenimientoActionPerformed(evt);
            }
        });

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empleado.png"))); // NOI18N
        jMenuItem9.setText("Usuario y Acceso");
        jMenuItem9.setToolTipText("Registrar Usuario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        mantenimiento.add(jMenuItem9);

        jMenuBar1.add(mantenimiento);

        M_acerca.setText("A Cerca de");
        M_acerca.setToolTipText("A Cerca De");
        M_acerca.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        M_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_acercaActionPerformed(evt);
            }
        });

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuItem8.setText("Acerca de ");
        jMenuItem8.setToolTipText("Acerca de ");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        M_acerca.add(jMenuItem8);

        jMenuBar1.add(M_acerca);

        jMenu1.setText("Ayuda");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImage1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArticulosActionPerformed
      Frm_Articulo arti = new Frm_Articulo(this,true);
      //arti.setLocationRelativeTo(this);
      arti.setVisible(true);
}//GEN-LAST:event_ArticulosActionPerformed

    private void ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesActionPerformed
    //  if (lb_tipo.getText().equals("Facturador")){
      //      Frm_cliente.btn_prueba.setEnabled(false);
        //  Frm_cliente.btn_editara.setEnabled(false);   
        Frm_cliente clien = new Frm_cliente(this, true);
       // clien.setLocationRelativeTo(this);
        clien.setVisible(true);   
     
     // }       
        
}//GEN-LAST:event_ClientesActionPerformed

    private void menu_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_empleadosActionPerformed
       Frm_Empleado emple=new Frm_Empleado(this,true);
       //emple.setLocationRelativeTo(this);
       emple.setVisible(true);
}//GEN-LAST:event_menu_empleadosActionPerformed

    private void ProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedoresActionPerformed
       Frm_Provedor prove = new Frm_Provedor(this, true);
       //prove.setLocationRelativeTo(this);
       prove.setVisible(true);
                              
}//GEN-LAST:event_ProveedoresActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Frm_tablacliente cc = new Frm_tablacliente(this, true);
        cc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    Frm_tablaEmpleado ce=new Frm_tablaEmpleado(this, true);
    ce.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    Frm_tabalaProvedor cp = new Frm_tabalaProvedor(this, true);
    cp.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
    Frm_tablaArticulo ca= new Frm_tablaArticulo(this, true);
    ca.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

       frm_reportefactura repor = new frm_reportefactura();
       repor .setVisible(true);
       repor.setLocationRelativeTo(this);
         
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       frm_reportearticulos articulo = new frm_reportearticulos();
       articulo.setVisible(true);
      
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

       frm_reportecliente cliente = new frm_reportecliente();
       cliente.setVisible(true);        

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Object[] opciones ={"Aceptar","Cancelar"};
        int eleccion = JOptionPane.showOptionDialog(rootPane,"En Realidad desea Salir de la Aplicacion","Alerta",

                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
        if(eleccion ==JOptionPane.YES_OPTION){
            System.exit(0);
        }else{

        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void M_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_acercaActionPerformed

   frm_acercade a = new frm_acercade(this, true);
   a.setVisible(true);
   a.setLocationRelativeTo(this);
   
// TODO add your handling code here:
    }//GEN-LAST:event_M_acercaActionPerformed

    private void mantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mantenimientoActionPerformed

        

// TODO add your handling code here:
    }//GEN-LAST:event_mantenimientoActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    frm_acercade acer= new frm_acercade(this, true);
    acer.setVisible(true);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        registrarse r = new registrarse();
        r.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed

Object[]opciones={"Aceptar","Cancelar"};
int mensa= JOptionPane.showOptionDialog(rootPane,"DESEA SALIR DEL SISTEMA??", "ADVERTENCIA",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null, opciones,"Aceptar");
if (mensa ==JOptionPane.YES_OPTION )
{System.exit(0);}
else 
{}

        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void M_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_desconectarActionPerformed
    M_desconectar.setEnabled(false);
    M_registrar.setEnabled(false);
    M_consultar.setEnabled(false);
    M_reportes.setEnabled(false);
    mantenimiento.setEnabled(false);
    M_acerca.setEnabled(false);
    M_conectar.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_M_desconectarActionPerformed

    private void M_conectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_conectarActionPerformed

    usuario usuarios = new usuario();
    usuarios.setVisible(true);
    this.dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_M_conectarActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        // Llamar aun pdf 
    try {
        File path = new File ("MANUAL.pdf");
        Desktop.getDesktop().open(path);
    }catch (IOException ex) {
        ex.printStackTrace();
    }

// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        new frm_remito ().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void FacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturasActionPerformed
        new Frm_facturap ().setVisible(true);  
    }//GEN-LAST:event_FacturasActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        new Frm_presupuesto ().setVisible(true); 
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void botonArticulos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos7ActionPerformed
        new Frm_presupuesto ().setVisible(true);
    }//GEN-LAST:event_botonArticulos7ActionPerformed

    private void botonArticulos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos3ActionPerformed
        Frm_cliente clien = new Frm_cliente(this, true);
       // clien.setLocationRelativeTo(this);
        clien.setVisible(true);
    }//GEN-LAST:event_botonArticulos3ActionPerformed

    private void botonArticulos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos1ActionPerformed
       Frm_Articulo arti = new Frm_Articulo(this,true);
      //arti.setLocationRelativeTo(this);
      arti.setVisible(true);
    }//GEN-LAST:event_botonArticulos1ActionPerformed

    private void botonArticulos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos2ActionPerformed
       Frm_Provedor prove = new Frm_Provedor(this, true);
       //prove.setLocationRelativeTo(this);
       prove.setVisible(true);
    }//GEN-LAST:event_botonArticulos2ActionPerformed

    private void botonArticulos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos6ActionPerformed
       Frm_Empleado emple=new Frm_Empleado(this,true);
       //emple.setLocationRelativeTo(this);
       emple.setVisible(true);
    }//GEN-LAST:event_botonArticulos6ActionPerformed

    private void botonArticulos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos5ActionPerformed
        new Frm_facturap ().setVisible(true);
    }//GEN-LAST:event_botonArticulos5ActionPerformed

    private void botonArticulos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos4ActionPerformed
        new frm_remito ().setVisible(true);
    }//GEN-LAST:event_botonArticulos4ActionPerformed

    private void botonArticulos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos8ActionPerformed
       frm_reportefactura repor = new frm_reportefactura();
       repor .setVisible(true);
       repor.setLocationRelativeTo(this);
    }//GEN-LAST:event_botonArticulos8ActionPerformed

    private void botonArticulos9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos9ActionPerformed
       frm_reportecliente cliente = new frm_reportecliente();
       cliente.setVisible(true);
    }//GEN-LAST:event_botonArticulos9ActionPerformed

    private void botonArticulos10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArticulos10ActionPerformed
       frm_reportecliente cliente = new frm_reportecliente();
       cliente.setVisible(true);
    }//GEN-LAST:event_botonArticulos10ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Clientes;
    private javax.swing.JMenuItem Facturas;
    private javax.swing.JMenu M_acerca;
    private javax.swing.JMenuItem M_conectar;
    private javax.swing.JMenu M_consultar;
    private javax.swing.JMenu M_deinicio;
    private javax.swing.JMenuItem M_desconectar;
    public static javax.swing.JMenu M_registrar;
    private javax.swing.JMenu M_reportes;
    public static javax.swing.JMenuItem Proveedores;
    private javax.swing.JButton botonArticulos1;
    private javax.swing.JButton botonArticulos10;
    private javax.swing.JButton botonArticulos2;
    private javax.swing.JButton botonArticulos3;
    private javax.swing.JButton botonArticulos4;
    private javax.swing.JButton botonArticulos5;
    private javax.swing.JButton botonArticulos6;
    private javax.swing.JButton botonArticulos7;
    private javax.swing.JButton botonArticulos8;
    private javax.swing.JButton botonArticulos9;
    public static javax.swing.JLabel conectado;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    public static javax.swing.JLabel lb_tipo;
    public static javax.swing.JMenu mantenimiento;
    public static javax.swing.JMenuItem menu_empleados;
    private javax.swing.JPanel panelBotones;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables

}
