 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * usuario.java
 *
 * Created on 13/05/2010, 11:44:23 AM
 */

package Vistas;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author Alberto
 */
public class usuario extends javax.swing.JFrame {

    /** Creates new form usuario */
    public usuario() {
        initComponents();
        setLocationRelativeTo(null);
      
     

//principal2 principal2 = new principal2();
       // this.add(principal2, BorderLayout.CENTER);
        this.pack();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImage3 = new org.edisoncor.gui.panel.PanelImage();
        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JTextField();
        txt_clave = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        panelImage7 = new org.edisoncor.gui.panel.PanelImage();
        cbo_tipo = new javax.swing.JComboBox();
        buttonSeven1 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven2 = new org.edisoncor.gui.button.ButtonSeven();
        panelImage8 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" ACCESO DE LOGEO....");
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        panelImage3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menumar.png"))); // NOI18N
        panelImage3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panelImage3);
        panelImage3.setBounds(0, 300, 700, 70);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 210, -1));

        txt_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_claveKeyPressed(evt);
            }
        });
        jPanel1.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 210, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("USUARIO");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 70, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("CLAVE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 50, 20));

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login.png"))); // NOI18N
        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 140, 170));

        panelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facc.png"))); // NOI18N
        jPanel1.add(panelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 130, 140));

        cbo_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Facturador" }));
        jPanel1.add(cbo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, 20));

        buttonSeven1.setBackground(new java.awt.Color(0, 204, 255));
        buttonSeven1.setText("Entrar");
        buttonSeven1.setColorBrillo(new java.awt.Color(255, 255, 255));
        buttonSeven1.setColorDeSombra(new java.awt.Color(255, 255, 255));
        buttonSeven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeven1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        buttonSeven2.setBackground(new java.awt.Color(255, 0, 0));
        buttonSeven2.setText("Salir");
        buttonSeven2.setColorBrillo(new java.awt.Color(255, 255, 255));
        buttonSeven2.setColorDeSombra(new java.awt.Color(255, 255, 255));
        buttonSeven2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven2ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeven2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 70, 610, 230);

        panelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menumar.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 30)); // NOI18N
        jLabel1.setText("ACCESO DE USUARIO");
        panelImage8.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/llave.png"))); // NOI18N
        panelImage8.add(jLabel2);

        getContentPane().add(panelImage8);
        panelImage8.setBounds(0, 0, 700, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
 if (evt.getKeyChar()==evt.VK_ENTER){
            if(nombre.getText().equals(""))
                JOptionPane.showMessageDialog(null,"Ingrese el Dato");
            else
                txt_clave.requestFocus();
        }                // TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyTyped

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased

        //nombre.setText(nombre.getText().toUpperCase());

// TODO add your handling code here:
    }//GEN-LAST:event_nombreKeyReleased

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyReleased

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void buttonSeven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven1ActionPerformed

       if(nombre.getText().equals("")){
             JOptionPane.showMessageDialog(this, "INGRESE SU USUARIO","Advertencia",JOptionPane.WARNING_MESSAGE );
            nombre.requestFocus();
            
                    }else
            
               if(txt_clave.getText().equals("")){
            JOptionPane.showMessageDialog(this, "INGRESE SU CONTRASEÑA","Advertencia",JOptionPane.WARNING_MESSAGE );
            txt_clave.requestFocus();
                    }else

        
        try{  
            //   String usu,con;
      //  String tusu,tcon;
        int num=0;
        
        
        String usuario=nombre.getText();
        String clave=txt_clave.getText();
        String tipo=String.valueOf(cbo_tipo.getSelectedItem());

            String bd ="ventas";
            String login = "root";
            String password = "";
            String url = "jdbc:mysql://localhost/"+bd; // esta es la conexion
            Class.forName("com.mysql.jdbc.Driver"); // este es el driver que copiaron y pegaron
            Connection conn=(Connection) DriverManager.getConnection(url,login,password); // esta es la verificación de la conexión con mysql
            Statement consulta=conn.createStatement(); // crea una variable que se encargue del código de sql
            ResultSet res= consulta.executeQuery("select * from usuarios where clave='"+clave+"' and usuario='"+usuario+"' and acceso='"+tipo+"' and estado='A'    ");
              
    
                          
            if (res.next()){
                menu form=new menu(); 
                form.setVisible(true);
                form.toFront();
                menu.conectado.setText(usuario);
                menu.lb_tipo.setText(tipo);
                if (!menu.lb_tipo.getText().equals("Administrador")){
                    menu.menu_empleados.setEnabled(false);
                     menu.Proveedores.setEnabled(false);
                   menu.mantenimiento.setEnabled(false);     
                   
                }
                
            }else {
              JOptionPane.showMessageDialog(this," El usuario"+" "+nombre.getText()+" "+"De Tipo" + " " + cbo_tipo.getSelectedItem()+" No Existe O verifique la Contraseña","INFORMACION",JOptionPane.ERROR_MESSAGE);
                    
             nombre.setText("");
            txt_clave.setText("");
             nombre.requestFocus();
      
            }
           
        
        
        
        }catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Error en el SQL") ;
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"No hay conexion con Mysql") ;
        }
        
          





// TODO add your handling code here:
    }//GEN-LAST:event_buttonSeven1ActionPerformed

    private void buttonSeven2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven2ActionPerformed

       System.exit(0);   

// TODO add your handling code here:
    }//GEN-LAST:event_buttonSeven2ActionPerformed

    private void txt_claveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claveKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER){
    
       if(nombre.getText().equals("")){
             JOptionPane.showMessageDialog(this, "INGRESE SU USUARIO","Advertencia",JOptionPane.WARNING_MESSAGE );
            nombre.requestFocus();
            
                    }else
            
               if(txt_clave.getText().equals("")){
            JOptionPane.showMessageDialog(this, "INGRESE SU CONTRASEÑA","Advertencia",JOptionPane.WARNING_MESSAGE );
            txt_clave.requestFocus();
                    }else

        
        try{  
            //   String usu,con;
      //  String tusu,tcon;
        int num=0;
        
        
        String usuario=nombre.getText();
        String clave=txt_clave.getText();
        String tipo=String.valueOf(cbo_tipo.getSelectedItem());

            String bd ="ventas";
            String login = "root";
            String password = "";
            String url = "jdbc:mysql://localhost/"+bd; // esta es la conexion
            Class.forName("com.mysql.jdbc.Driver"); // este es el driver que copiaron y pegaron
            Connection conn=(Connection) DriverManager.getConnection(url,login,password); // esta es la verificación de la conexión con mysql
            Statement consulta=conn.createStatement(); // crea una variable que se encargue del código de sql
            ResultSet res= consulta.executeQuery("select * from usuarios where clave='"+clave+"' and usuario='"+usuario+"' and acceso='"+tipo+"' and estado='A'    ");
              
    
                          
            if (res.next()){
                menu form=new menu(); 
                form.setVisible(true);
                form.toFront();
                menu.conectado.setText(usuario);
                menu.lb_tipo.setText(tipo);
                if (!menu.lb_tipo.getText().equals("Administrador")){
                    menu.menu_empleados.setEnabled(false);
                     menu.Proveedores.setEnabled(false);
                   menu.mantenimiento.setEnabled(false);     
                   
                }
                
            }else {
              JOptionPane.showMessageDialog(this," El usuario"+" "+nombre.getText()+" "+"De Tipo" + " " + cbo_tipo.getSelectedItem()+" No Existe O verifique la Contraseña","INFORMACION",JOptionPane.ERROR_MESSAGE);
                    
             nombre.setText("");
            txt_clave.setText("");
             nombre.requestFocus();
      
            }
           
        
        
        
        }catch(SQLException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null,"Error en el SQL") ;
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null,"No hay conexion con Mysql") ;
        }
        
}        // TODO add your handling code here:
    }//GEN-LAST:event_txt_claveKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonSeven buttonSeven1;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven2;
    public static javax.swing.JComboBox cbo_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage3;
    private org.edisoncor.gui.panel.PanelImage panelImage7;
    private org.edisoncor.gui.panel.PanelImage panelImage8;
    private javax.swing.JPasswordField txt_clave;
    // End of variables declaration//GEN-END:variables

}
